---
name: Galaxy-NG Roles Import

# yamllint disable-line rule:truthy
on:
  release:
    types: ['created']

jobs:
  build:
    name: Galaxy Role Importer
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 'Install Ansible'
        run: pip install ansible

      - name: 'Import role to Galaxy'
        env:
          GALAXY_API_KEY: ${{ secrets.galaxy_api_key }}
        run: |
          ansible-galaxy role import \
            --api-key "$GALAXY_API_KEY" \
            --role-name harvesterpy \
            bpmconsultag HarvesterPy